# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your Awesome Force
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The awesomest mercenary force every assembled in the Inner Sphere. Maybe even the Outer Sphere!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
banner_image: true
logo: /assets/images/unit_logo.png

# By default, the description in the top-level force will be placed on the home 
# page rather than the TO&E page. Switch to false to turn this behavior off.
toe_front_page: true


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

#important for this to be on if you want to date blog entries from ... the future!
future: true

collections_dir: campaign

collections:
  personnel:
    output: true
  missions:
    output: true
  scenarios:
    output: true
  forces:
    output: true
  tro:
    output: true

sass:
  sass_dir: css
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
